# Generated by Django 4.1 on 2022-08-26 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_webrequest_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
