# Generated by Django 2.2 on 2021-09-06 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, editable=False, max_length=128, unique=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_pic')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('storage_allowed', models.IntegerField(default=10)),
                ('bandwidth_allowed', models.IntegerField(default=100)),
                ('requests_allowed', models.IntegerField(default=1000)),
                ('bandwidth_used', models.FloatField(default=0)),
                ('requests_used', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
    ]
