# Generated by Django 2.2 on 2021-10-10 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='bandwidth_allowed',
        ),
        migrations.RemoveField(
            model_name='account',
            name='bandwidth_used',
        ),
        migrations.RemoveField(
            model_name='account',
            name='requests_allowed',
        ),
        migrations.RemoveField(
            model_name='account',
            name='requests_used',
        ),
        migrations.RemoveField(
            model_name='account',
            name='storage_allowed',
        ),
    ]
