# Generated by Django 2.2 on 2021-10-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolsframe', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='upcomingtool',
            index=models.Index(fields=['active'], name='active_idx'),
        ),
    ]
