# Generated by Django 2.2 on 2021-10-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolsframe', '0002_auto_20211003_1451'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='upcomingtool',
            name='active_idx',
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['active'], name='tool_active_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['tool_id'], name='tool_id_idx'),
        ),
        migrations.AddIndex(
            model_name='upcomingtool',
            index=models.Index(fields=['active'], name='upcoming_active_idx'),
        ),
    ]
