# Generated by Django 2.2 on 2021-10-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolsframe', '0003_auto_20211003_1457'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tool',
            name='tool_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='tool',
            name='tool_id_idx',
        ),
        migrations.AlterField(
            model_name='tool',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='tool_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=128, unique=True),
        ),
    ]
