# Generated by Django 4.1 on 2022-09-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolsframe', '0006_delete_toolviewsfunctions'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='manager_class',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
