# Generated by Django 4.1 on 2022-09-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolsframe', '0007_tool_manager_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='has_db',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ToolDatabaseClass',
        ),
    ]
