# Generated by Django 2.2 on 2021-10-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_fhostmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fhostmodel',
            name='allowed_origins',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fhostmodel',
            name='file_name',
            field=models.CharField(db_index=True, max_length=80, unique=True),
        ),
    ]
